//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.rogers.cashintegration.bpsservice.model;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BatchDownloadType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="BatchDownloadType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="fileAttached" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="formatId" type="{http://www.semafone.com}FormatType"/>
 *         <element name="fileType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BatchDownloadType", propOrder = {
    "fileAttached",
    "formatId",
    "fileType"
})
public class BatchDownloadType {

    @XmlElement(required = true)
    protected String fileAttached;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected FormatType formatId;
    @XmlElement(required = true)
    protected String fileType;

    /**
     * Gets the value of the fileAttached property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileAttached() {
        return fileAttached;
    }

    /**
     * Sets the value of the fileAttached property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileAttached(String value) {
        this.fileAttached = value;
    }

    /**
     * Gets the value of the formatId property.
     * 
     * @return
     *     possible object is
     *     {@link FormatType }
     *     
     */
    public FormatType getFormatId() {
        return formatId;
    }

    /**
     * Sets the value of the formatId property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormatType }
     *     
     */
    public void setFormatId(FormatType value) {
        this.formatId = value;
    }

    /**
     * Gets the value of the fileType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * Sets the value of the fileType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileType(String value) {
        this.fileType = value;
    }

}
