//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.rogers.cashintegration.bpsservice.model;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rogers.cashintegration.bpsservice.model package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rogers.cashintegration.bpsservice.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CashBatchPutFileRequest }
     * 
     * @return
     *     the new instance of {@link CashBatchPutFileRequest }
     */
    public CashBatchPutFileRequest createCashBatchPutFileRequest() {
        return new CashBatchPutFileRequest();
    }

    /**
     * Create an instance of {@link CashBatchPutFileResponse }
     * 
     * @return
     *     the new instance of {@link CashBatchPutFileResponse }
     */
    public CashBatchPutFileResponse createCashBatchPutFileResponse() {
        return new CashBatchPutFileResponse();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     * @return
     *     the new instance of {@link ErrorType }
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link CashBatchListFilesRequest }
     * 
     * @return
     *     the new instance of {@link CashBatchListFilesRequest }
     */
    public CashBatchListFilesRequest createCashBatchListFilesRequest() {
        return new CashBatchListFilesRequest();
    }

    /**
     * Create an instance of {@link CashBatchListFilesResponse }
     * 
     * @return
     *     the new instance of {@link CashBatchListFilesResponse }
     */
    public CashBatchListFilesResponse createCashBatchListFilesResponse() {
        return new CashBatchListFilesResponse();
    }

    /**
     * Create an instance of {@link FileNameListType }
     * 
     * @return
     *     the new instance of {@link FileNameListType }
     */
    public FileNameListType createFileNameListType() {
        return new FileNameListType();
    }

    /**
     * Create an instance of {@link CashBatchGetFileRequest }
     * 
     * @return
     *     the new instance of {@link CashBatchGetFileRequest }
     */
    public CashBatchGetFileRequest createCashBatchGetFileRequest() {
        return new CashBatchGetFileRequest();
    }

    /**
     * Create an instance of {@link CashBatchGetFileResponse }
     * 
     * @return
     *     the new instance of {@link CashBatchGetFileResponse }
     */
    public CashBatchGetFileResponse createCashBatchGetFileResponse() {
        return new CashBatchGetFileResponse();
    }

    /**
     * Create an instance of {@link BatchDownloadType }
     * 
     * @return
     *     the new instance of {@link BatchDownloadType }
     */
    public BatchDownloadType createBatchDownloadType() {
        return new BatchDownloadType();
    }

}
